# Generated by Django 5.1.2 on 2024-12-02 21:37

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="category"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Category",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tax_rate", models.IntegerField(default=5)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("code", models.CharField(max_length=50)),
                ("discount", models.IntegerField(default=1)),
                ("active", models.BooleanField(default=False)),
                (
                    "date",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "used_by",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "initial_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "saved",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Paid", "Paid"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "strip_session_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("coupons", models.ManyToManyField(blank=True, to="api.coupon")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="course/file"),
                ),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="course/logo"),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Arabic", "Arabic"),
                            ("Spanish", "Spanish"),
                            ("French", "French"),
                            ("Bangla", "Bangla"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Begining", "Begining"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform_status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Published", "Published")],
                        max_length=20,
                    ),
                ),
                (
                    "teacher_course_status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Published", "Published")],
                        max_length=12,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "course_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "certificate_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issued", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartOrderItem",
            fields=[
                (
                    "tax_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "initial_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "saved",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("applied_coupon", models.BooleanField(default=False)),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderItem",
                        to="api.cartorder",
                    ),
                ),
                (
                    "coupons",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.coupon",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="api.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cart_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("title", models.CharField(max_length=1000)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "note_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="annoymous",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QA",
            fields=[
                ("question", models.CharField(max_length=200)),
                (
                    "qa_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="annomouse",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="QAM",
            fields=[
                ("answer", models.CharField(max_length=200)),
                (
                    "qa_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.qa"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="annomouse",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None
                    ),
                ),
                ("repy", models.CharField(blank=True, max_length=1000, null=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "date",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="annoymous",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(blank=True, null=True, upload_to="teacher")),
                ("full_name", models.CharField(blank=True, max_length=40, null=True)),
                ("bio", models.CharField(blank=True, max_length=100, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("linkedIn", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("New Order", "New Order"),
                            ("New Review", "New Review"),
                            ("New Course Question", "New Course Question"),
                            ("Draft", "Draft"),
                            ("Course Published", "Course Published"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                (
                    "date",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.cartorder",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.cartorderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="annoymous",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.review",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrolledCourse",
            fields=[
                (
                    "enrolled_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cartorderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.teacher"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.teacher",
            ),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.teacher"
            ),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.teacher",
            ),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("title", models.CharField(max_length=30, unique=True)),
                (
                    "varient_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantItem",
            fields=[
                ("title", models.CharField(max_length=50)),
                ("info", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="varientItem"),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "content_duration",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("preview", models.BooleanField(default=False)),
                (
                    "variant_item_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_items",
                        to="api.variant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "variant_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.variantitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
