# Generated by Django 5.1.2 on 2024-12-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cartorder_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
