# Generated by Django 5.1.3 on 2024-11-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_full_name_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
